#pragma once

#include <SDL2/SDL.h>

#define STD_BLOCK_W 20
#define STD_BLOCK_H 20 
#define STD_LINE_THICKNESS 10
#define BLENDMODE SDL_BLENDMODE_BLEND
#define OPAQUE SDL_ALPHA_OPAQUE
#define TRANSPARENT SDL_ALPHA_TRANSPARENT